spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/win_testng?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
  data:
    mongodb:
      repositories:
        enabled: false
  redis:
    host: localhost
    port: 3736
    password: 123456
    database: 10
project:
  filePath: files
  reportDomain: https://testplatform-api.winbaoxian.cn